/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/obj/Alliance_White_Gold_Ring.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

// Preload the model
useGLTF.preload('/obj/Alliance_White_Gold_Ring.glb');

export function Model({ children }) {
  const { nodes, materials } = useGLTF('/obj/Alliance_White_Gold_Ring.glb');
  
  // Render the model with children as material
  return (
    <group dispose={null}>
      <mesh 
        geometry={nodes.Ring.geometry} 
        position={[-0.012, 0.643, 0.003]}
      >
        {children}
        <mesh geometry={nodes.Diamond_Holder.geometry}>
          {children}
        </mesh>
        <mesh geometry={nodes.Diamonds.geometry}>
          <meshStandardMaterial 
            color="#ffffff" 
            emissive="#ffffff"
            emissiveIntensity={0.2}
            roughness={0.1}
            metalness={0.9}
          />
        </mesh>
      </mesh>
    </group>
  );
}
